export const GUEST_PAST_TASK = "GUEST_PAST_TASK";
export const GUEST_TODAY_TASK = "GUEST_TODAY_TASK";
export const GUEST_TOMORROW_TASK = "GUEST_TOMORROW_TASK";
export const GUEST_WEEK_TASK = "GUEST_WEEK_TASK";